apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: sentiment-comprehensive-chaos
  namespace: default
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 30m
      children:
        - pod-kill-test
        - network-delay-test
        - stress-test
        - recovery-check

    - name: pod-kill-test
      templateType: PodChaos
      deadline: 5m
      podChaos:
        action: pod-kill
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app.kubernetes.io/name: mlops-sentiment
        duration: '30s'

    - name: network-delay-test
      templateType: NetworkChaos
      deadline: 5m
      networkChaos:
        action: delay
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app.kubernetes.io/name: mlops-sentiment
        delay:
          latency: '200ms'
          correlation: '25'
          jitter: '20ms'
        duration: '3m'

    - name: stress-test
      templateType: StressChaos
      deadline: 5m
      stressChaos:
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app.kubernetes.io/name: mlops-sentiment
        stressors:
          cpu:
            workers: 2
            load: 80
        duration: '3m'

    - name: recovery-check
      templateType: Suspend
      deadline: 5m
      suspend:
        duration: '2m'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: sentiment-disaster-scenario
  namespace: default
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Parallel
      deadline: 10m
      children:
        - pod-failure
        - network-partition
        - cpu-stress

    - name: pod-failure
      templateType: PodChaos
      deadline: 5m
      podChaos:
        action: pod-failure
        mode: fixed
        value: '1'
        selector:
          namespaces:
            - default
          labelSelectors:
            app.kubernetes.io/name: mlops-sentiment
        duration: '5m'

    - name: network-partition
      templateType: NetworkChaos
      deadline: 5m
      networkChaos:
        action: partition
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app.kubernetes.io/name: mlops-sentiment
        direction: to
        target:
          mode: all
          selector:
            namespaces:
              - default
            labelSelectors:
              app: redis
        duration: '3m'

    - name: cpu-stress
      templateType: StressChaos
      deadline: 5m
      stressChaos:
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app.kubernetes.io/name: mlops-sentiment
        stressors:
          cpu:
            workers: 2
            load: 90
        duration: '4m'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: sentiment-scheduled-chaos
  namespace: default
spec:
  schedule: '@every 6h'
  type: Workflow
  historyLimit: 10
  concurrencyPolicy: Forbid
  workflowSpec:
    entry: entry
    templates:
      - name: entry
        templateType: Serial
        deadline: 20m
        children:
          - random-chaos
          - wait
          - health-check

      - name: random-chaos
        templateType: PodChaos
        deadline: 5m
        podChaos:
          action: pod-kill
          mode: one
          selector:
            namespaces:
              - default
            labelSelectors:
              app.kubernetes.io/name: mlops-sentiment
          duration: '30s'

      - name: wait
        templateType: Suspend
        deadline: 2m
        suspend:
          duration: '1m'

      - name: health-check
        templateType: Suspend
        deadline: 1m
        suspend:
          duration: '30s'
