version: "3.8"

services:
  sentiment-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLOPS_DEBUG=true
      - MLOPS_LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app/app:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
