{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "mlops-sentiment.fullname" . }}-alerts
  labels:
    {{- include "mlops-sentiment.labels" . | nindent 4 }}
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: mlops-sentiment.rules
    interval: 30s
    rules:
    # Service Health Alerts
    - alert: MLOpsServiceDown
      expr: up{job="mlops-sentiment"} == 0
      for: 1m
      labels:
        severity: critical
        service: mlops-sentiment
      annotations:
        summary: "MLOps Sentiment service is down"
        description: "MLOps Sentiment service has been down for more than 1 minute. Instance: {{ $labels.instance }}"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#service-down"

    - alert: MLOpsHighErrorRate
      expr: rate(http_requests_total{job="mlops-sentiment",status=~"5.."}[5m]) / rate(http_requests_total{job="mlops-sentiment"}[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
        service: mlops-sentiment
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }} for more than 5 minutes"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#high-error-rate"

    - alert: MLOpsHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="mlops-sentiment"}[5m])) > 0.5
      for: 10m
      labels:
        severity: warning
        service: mlops-sentiment
      annotations:
        summary: "High latency detected"
        description: "95th percentile latency is {{ $value }}s for more than 10 minutes"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#high-latency"

    # ML Model Specific Alerts
    - alert: MLModelInferenceSlowdown
      expr: rate(mlops_inference_duration_seconds_sum{job="mlops-sentiment"}[5m]) / rate(mlops_inference_duration_seconds_count{job="mlops-sentiment"}[5m]) > 0.2
      for: 5m
      labels:
        severity: warning
        service: mlops-sentiment
        component: ml-model
      annotations:
        summary: "ML model inference is slow"
        description: "Average inference time is {{ $value }}s, which is above the 200ms threshold"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#slow-inference"

    - alert: MLModelNotLoaded
      expr: mlops_model_loaded{job="mlops-sentiment"} == 0
      for: 1m
      labels:
        severity: critical
        service: mlops-sentiment
        component: ml-model
      annotations:
        summary: "ML model is not loaded"
        description: "ML model failed to load or became unavailable on instance {{ $labels.instance }}"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#model-not-loaded"

    # Resource Usage Alerts
    - alert: MLOpsHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"mlops-sentiment-.*"}[5m]) * 100 > 80
      for: 10m
      labels:
        severity: warning
        service: mlops-sentiment
        component: resources
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is {{ $value }}% on pod {{ $labels.pod }}"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#high-cpu"

    - alert: MLOpsHighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"mlops-sentiment-.*"} / container_spec_memory_limit_bytes{pod=~"mlops-sentiment-.*"} * 100 > 85
      for: 10m
      labels:
        severity: warning
        service: mlops-sentiment
        component: resources
      annotations:
        summary: "High memory usage detected"
        description: "Memory usage is {{ $value }}% on pod {{ $labels.pod }}"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#high-memory"

    - alert: MLOpsPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{pod=~"mlops-sentiment-.*"}[15m]) > 0
      for: 5m
      labels:
        severity: critical
        service: mlops-sentiment
        component: stability
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#crash-loop"

    # Business Logic Alerts
    - alert: MLOpsLowPredictionConfidence
      expr: rate(mlops_prediction_confidence_sum{job="mlops-sentiment"}[5m]) / rate(mlops_prediction_confidence_count{job="mlops-sentiment"}[5m]) < 0.7
      for: 15m
      labels:
        severity: warning
        service: mlops-sentiment
        component: ml-quality
      annotations:
        summary: "Low prediction confidence detected"
        description: "Average prediction confidence is {{ $value }}, which is below the 0.7 threshold"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#low-confidence"

    - alert: MLOpsNoTrafficReceived
      expr: rate(http_requests_total{job="mlops-sentiment"}[10m]) == 0
      for: 15m
      labels:
        severity: warning
        service: mlops-sentiment
        component: traffic
      annotations:
        summary: "No traffic received"
        description: "No HTTP requests received for more than 15 minutes"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#no-traffic"

    # Security Alerts
    - alert: MLOpsUnauthorizedAccess
      expr: rate(http_requests_total{job="mlops-sentiment",status="401"}[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
        service: mlops-sentiment
        component: security
      annotations:
        summary: "Unauthorized access attempts detected"
        description: "{{ $value }} unauthorized requests per second detected"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#unauthorized-access"

    - alert: MLOpsSuspiciousTrafficPattern
      expr: rate(http_requests_total{job="mlops-sentiment"}[1m]) > 100
      for: 2m
      labels:
        severity: warning
        service: mlops-sentiment
        component: security
      annotations:
        summary: "Suspicious traffic pattern detected"
        description: "Very high request rate: {{ $value }} requests per second"
        runbook_url: "https://github.com/arec1b0/KubeSentiment/wiki/runbooks#suspicious-traffic"
{{- end }}
