# Development Kubernetes Configuration
# Usage: kubectl apply -f kubernetes-dev.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: mlops-dev

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-sentiment-config
  namespace: mlops-dev
data:
  MLOPS_PROFILE: "development"
  MLOPS_DEBUG: "true"
  MLOPS_LOG_LEVEL: "DEBUG"
  MLOPS_ENABLE_METRICS: "true"
  MLOPS_ENABLE_PROFILING: "true"
  MLOPS_MODEL_BACKEND: "pytorch"
  MLOPS_REDIS_ENABLED: "true"
  MLOPS_REDIS_HOST: "redis"
  MLOPS_REDIS_PORT: "6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-sentiment
  namespace: mlops-dev
  labels:
    app: mlops-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-sentiment
  template:
    metadata:
      labels:
        app: mlops-sentiment
    spec:
      containers:
      - name: api
        image: mlops-sentiment:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: mlops-sentiment-config
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-sentiment
  namespace: mlops-dev
  labels:
    app: mlops-sentiment
spec:
  type: ClusterIP
  selector:
    app: mlops-sentiment
  ports:
  - name: http
    port: 80
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mlops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mlops-dev
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
