# Staging Kubernetes Configuration
# Usage: kubectl apply -f kubernetes-staging.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: mlops-staging

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-sentiment-config
  namespace: mlops-staging
data:
  MLOPS_PROFILE: "staging"
  MLOPS_DEBUG: "false"
  MLOPS_LOG_LEVEL: "INFO"
  MLOPS_ENVIRONMENT: "staging"
  MLOPS_WORKERS: "2"
  MLOPS_ENABLE_METRICS: "true"
  MLOPS_ENABLE_TRACING: "true"
  MLOPS_TRACING_BACKEND: "jaeger"
  MLOPS_MODEL_BACKEND: "onnx"
  MLOPS_REDIS_ENABLED: "true"
  MLOPS_REDIS_HOST: "redis-staging"
  MLOPS_REDIS_PORT: "6379"
  MLOPS_VAULT_ENABLED: "true"
  MLOPS_VAULT_ADDR: "https://vault-staging.example.com"
  MLOPS_MLFLOW_ENABLED: "true"
  MLOPS_MLFLOW_TRACKING_URI: "https://mlflow-staging.example.com"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-sentiment
  namespace: mlops-staging
  labels:
    app: mlops-sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-sentiment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mlops-sentiment
    spec:
      containers:
      - name: api
        image: gcr.io/my-project/mlops-sentiment:staging-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: mlops-sentiment-config
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-sentiment
  namespace: mlops-staging
  labels:
    app: mlops-sentiment
spec:
  type: LoadBalancer
  selector:
    app: mlops-sentiment
  ports:
  - name: http
    port: 80
    targetPort: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mlops-sentiment-hpa
  namespace: mlops-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-sentiment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mlops-sentiment-pdb
  namespace: mlops-staging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mlops-sentiment
