apiVersion: v1
kind: Namespace
metadata:
  name: mlops-sentiment
  labels:
    app: sentiment-service
    version: v1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlops-sentiment-quota
  namespace: mlops-sentiment
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
    pods: "10"
