# Production Environment Configuration
# Конфигурация для production окружения

name: production

# URL окружения
url: https://sentiment-api.yourdomain.com

# Правила защиты (максимальная безопасность)
protection_rules:
  # Разрешенные ветки для развертывания
  deployment_branches:
    - main

  # Разрешенные теги
  deployment_tags:
    - v*.*.* # Только семантические версии

  # Требования к reviewers
  required_reviewers:
    count: 2
    users:
      - senior-devops
      - tech-lead
    teams:
      - production-approvers
      - security-team

  # Задержка перед развертыванием (в минутах)
  wait_timer: 10

  # Дополнительные проверки
  prevent_self_review: true
  dismiss_stale_reviews: true
  require_code_owner_reviews: true

# Переменные окружения
variables:
  ENVIRONMENT: production
  LOG_LEVEL: WARN
  REPLICAS: 3
  CPU_REQUEST: 1000m
  CPU_LIMIT: 2000m
  MEMORY_REQUEST: 2Gi
  MEMORY_LIMIT: 4Gi

  # Kubernetes настройки
  NAMESPACE: mlops-sentiment
  INGRESS_HOST: sentiment-api.yourdomain.com

  # Мониторинг
  METRICS_ENABLED: true
  PROMETHEUS_SCRAPE: true
  GRAFANA_DASHBOARD: true
  JAEGER_TRACING: true

  # Production особенности
  AUTO_RELOAD: false
  DEBUG_MODE: false
  ENABLE_PROFILING: false
  HEALTH_CHECK_INTERVAL: 15

  # SSL/TLS
  TLS_ENABLED: true
  CERT_MANAGER_ISSUER: letsencrypt-prod
  HSTS_ENABLED: true

  # Безопасность
  SECURITY_HEADERS: true
  RATE_LIMITING: true
  CORS_STRICT: true

  # Производительность
  CONNECTION_POOL_SIZE: 20
  CACHE_ENABLED: true
  CACHE_TTL: 300

# Секреты
secrets:
  - KUBE_CONFIG
  - SLACK_WEBHOOK_URL
  - DB_PASSWORD
  - API_KEY
  - SSL_CERT_KEY
  - ENCRYPTION_KEY # Для шифрования данных
  - JWT_SECRET # Для аутентификации
  - MONITORING_TOKEN # Для внешнего мониторинга

# Дополнительные настройки
settings:
  # Стратегия развертывания
  deployment_strategy: blue_green
  blue_green_timeout: 600 # 10 минут на переключение

  # Автоматическое тестирование
  post_deployment_tests: true
  smoke_tests_enabled: true
  integration_tests_enabled: true
  load_tests_enabled: true
  security_tests_enabled: true

  # Лимиты и таймауты
  max_concurrent_deployments: 1
  deployment_timeout_minutes: 30
  rollback_on_failure: true
  auto_rollback_threshold: 5 # Откат при 5% ошибок

  # Канареечное развертывание
  canary_deployment:
    enabled: true
    initial_traffic: 10%
    increment_step: 25%
    increment_interval: 300 # 5 минут
    success_threshold: 99%

  # Уведомления
  notifications:
    slack:
      channel: "#production-deployments"
      on_success: true
      on_failure: true
      include_metrics: true
      mention_on_failure: "@here"

    email:
      recipients:
        - devops@company.com
        - oncall@company.com
      on_failure: true

    github:
      create_deployment_status: true
      create_release_notes: true
      tag_release: true

  # Мониторинг и алерты
  monitoring:
    health_checks:
      - endpoint: /health
        interval: 15s
        timeout: 5s
        failure_threshold: 3
      - endpoint: /metrics
        interval: 30s
        timeout: 10s
      - endpoint: /ready
        interval: 10s
        timeout: 3s

    alerts:
      - name: service_down
        condition: up == 0
        duration: 1m
        severity: critical
      - name: high_error_rate
        condition: error_rate > 1%
        duration: 2m
        severity: critical
      - name: high_latency
        condition: p95_latency > 500ms
        duration: 5m
        severity: warning
      - name: memory_usage_high
        condition: memory_usage > 80%
        duration: 5m
        severity: warning
      - name: cpu_usage_high
        condition: cpu_usage > 80%
        duration: 5m
        severity: warning

  # Backup и восстановление
  backup:
    enabled: true
    schedule: "0 2 * * *" # Каждый день в 2:00
    retention_days: 30

  # Соответствие требованиям
  compliance:
    data_retention_days: 365
    audit_logging: true
    encryption_at_rest: true
    encryption_in_transit: true

  # SLA метрики
  sla:
    availability: 99.9%
    response_time_p95: 500ms
    error_rate_max: 0.1%
