# Async Batch Processing Configuration
# This configuration enables 85% performance improvement (10s → 1.5s)

# Async batch processing settings
async_batch:
  enabled: true

  # Job management
  max_jobs: 1000              # Maximum concurrent jobs
  max_batch_size: 1000        # Maximum batch size
  default_timeout_seconds: 300 # 5 minutes default timeout

  # Priority queue limits
  priority_high_limit: 100    # High priority queue size
  priority_medium_limit: 500  # Medium priority queue size
  priority_low_limit: 1000    # Low priority queue size

  # Cleanup and maintenance
  cleanup_interval_seconds: 60 # Clean up expired jobs every minute
  cache_ttl_seconds: 3600     # Cache results for 1 hour
  result_cache_max_size: 1000 # Maximum cached results

# Performance optimization settings
performance:
  # Response time targets
  target_response_time_seconds: 1.5  # Target 1.5s response time
  baseline_sync_time_seconds: 10.0   # Baseline sync processing time

  # Throughput targets
  target_throughput_tps: 1000       # Target 1000 TPS for async processing
  max_concurrent_batches: 50         # Maximum concurrent batch operations

  # Batching optimization
  optimal_batch_size_range: [50, 500]  # Optimal batch size range
  adaptive_batching: true              # Enable adaptive batch sizing

# API rate limiting
rate_limits:
  max_requests_per_minute: 1000      # Global rate limit
  max_batch_size_per_request: 1000   # Max batch size per request
  max_concurrent_users: 100          # Max concurrent users

# Monitoring and alerting
monitoring:
  # Performance thresholds
  max_response_time_seconds: 5.0     # Alert if > 5s
  min_throughput_tps: 100            # Alert if < 100 TPS
  max_error_rate: 0.05               # Alert if > 5% error rate

  # Health check settings
  health_check_interval_seconds: 30  # Health check every 30s
  metrics_collection_interval_seconds: 10  # Metrics every 10s

# Caching configuration
caching:
  enabled: true
  cache_results: true                # Cache completed job results
  cache_job_status: true             # Cache job status updates
  cache_ttl_seconds: 3600           # Cache TTL

# Error handling
error_handling:
  max_retries: 3                    # Maximum retry attempts
  retry_delay_seconds: 2            # Delay between retries
  enable_dead_letter_queue: true    # Send failed jobs to DLQ
  dlq_topic: "async_batch_failures" # Dead letter queue topic

# Resource allocation
resources:
  # CPU and memory for async processing
  cpu_request: "1000m"              # 1 CPU core
  memory_request: "2Gi"             # 2GB RAM
  cpu_limit: "2000m"                # 2 CPU cores max
  memory_limit: "4Gi"               # 4GB RAM max

  # Worker configuration
  background_workers: 8             # Background worker threads
  priority_worker_ratio: 0.3        # High priority worker ratio
