# Multi-Environment Deployment Workflow
# Автоматическое развертывание в различные окружения

name: Deploy to Environments

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Target environment (dev, staging, prod)'
      image_tag:
        required: true
        type: string
        description: 'Docker image tag to deploy'
      replicas:
        required: false
        type: number
        default: 2
        description: 'Number of replicas'
    secrets:
      KUBE_CONFIG:
        required: true
      SLACK_WEBHOOK_URL:
        required: false

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
        - dev
        - staging
        - prod
      image_tag:
        description: 'Docker image tag'
        required: true
        type: string
      replicas:
        description: 'Number of replicas'
        required: false
        type: number
        default: 2

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        kubectl cluster-info

    - name: Prepare environment-specific configurations
      run: |
        ENV="${{ inputs.environment }}"
        REPLICAS="${{ inputs.replicas }}"
        IMAGE_TAG="${{ inputs.image_tag }}"
        
        echo "Preparing deployment for environment: $ENV"
        
        # Создаем копии манифестов для модификации
        cp -r k8s/ k8s-$ENV/
        
        # Обновляем образ
        sed -i "s|sentiment-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}|g" k8s-$ENV/deployment.yaml
        
        # Настройки по окружениям
        case $ENV in
          "dev")
            # Development: минимальные ресурсы
            sed -i "s|replicas: 2|replicas: 1|g" k8s-$ENV/deployment.yaml
            sed -i "s|cpu: \"500m\"|cpu: \"250m\"|g" k8s-$ENV/deployment.yaml
            sed -i "s|memory: \"1Gi\"|memory: \"512Mi\"|g" k8s-$ENV/deployment.yaml
            sed -i "s|cpu: \"1000m\"|cpu: \"500m\"|g" k8s-$ENV/deployment.yaml
            sed -i "s|memory: \"2Gi\"|memory: \"1Gi\"|g" k8s-$ENV/deployment.yaml
            # Добавляем суффикс к namespace
            sed -i "s|namespace: mlops-sentiment|namespace: mlops-sentiment-dev|g" k8s-$ENV/*.yaml
            ;;
          "staging")
            # Staging: средние ресурсы
            sed -i "s|replicas: 2|replicas: 2|g" k8s-$ENV/deployment.yaml
            sed -i "s|namespace: mlops-sentiment|namespace: mlops-sentiment-staging|g" k8s-$ENV/*.yaml
            ;;
          "prod")
            # Production: максимальные ресурсы
            sed -i "s|replicas: 2|replicas: ${REPLICAS}|g" k8s-$ENV/deployment.yaml
            sed -i "s|cpu: \"500m\"|cpu: \"1000m\"|g" k8s-$ENV/deployment.yaml
            sed -i "s|memory: \"1Gi\"|memory: \"2Gi\"|g" k8s-$ENV/deployment.yaml
            sed -i "s|cpu: \"1000m\"|cpu: \"2000m\"|g" k8s-$ENV/deployment.yaml
            sed -i "s|memory: \"2Gi\"|memory: \"4Gi\"|g" k8s-$ENV/deployment.yaml
            # Production использует основной namespace
            ;;
        esac
        
        # Показываем итоговую конфигурацию
        echo "=== Final Deployment Configuration ==="
        cat k8s-$ENV/deployment.yaml

    - name: Deploy to ${{ inputs.environment }}
      run: |
        export KUBECONFIG=kubeconfig
        ENV="${{ inputs.environment }}"
        
        echo "🚀 Starting deployment to $ENV environment..."
        
        # Создаем namespace если не существует
        kubectl apply -f k8s-$ENV/namespace.yaml
        
        # Применяем конфигурации
        kubectl apply -f k8s-$ENV/configmap.yaml
        kubectl apply -f k8s-$ENV/deployment.yaml
        kubectl apply -f k8s-$ENV/service.yaml
        kubectl apply -f k8s-$ENV/hpa.yaml
        
        # Ingress только для staging и prod
        if [[ "$ENV" != "dev" ]]; then
          kubectl apply -f k8s-$ENV/ingress.yaml
        fi
        
        # Ждем успешного развертывания
        NAMESPACE="mlops-sentiment"
        if [[ "$ENV" != "prod" ]]; then
          NAMESPACE="mlops-sentiment-$ENV"
        fi
        
        echo "⏳ Waiting for deployment to complete in namespace: $NAMESPACE"
        kubectl rollout status deployment/sentiment-service -n $NAMESPACE --timeout=300s

    - name: Verify deployment
      run: |
        export KUBECONFIG=kubeconfig
        ENV="${{ inputs.environment }}"
        
        NAMESPACE="mlops-sentiment"
        if [[ "$ENV" != "prod" ]]; then
          NAMESPACE="mlops-sentiment-$ENV"
        fi
        
        echo "📊 Deployment verification for $ENV:"
        kubectl get pods -n $NAMESPACE -o wide
        kubectl get services -n $NAMESPACE
        
        # Проверяем HPA
        kubectl get hpa -n $NAMESPACE
        
        # Получаем логи последнего пода для проверки
        POD_NAME=$(kubectl get pods -n $NAMESPACE -l app=sentiment-service -o jsonpath='{.items[0].metadata.name}')
        echo "📋 Recent logs from $POD_NAME:"
        kubectl logs $POD_NAME -n $NAMESPACE --tail=20

    - name: Run health checks
      run: |
        export KUBECONFIG=kubeconfig
        ENV="${{ inputs.environment }}"
        
        NAMESPACE="mlops-sentiment"
        if [[ "$ENV" != "prod" ]]; then
          NAMESPACE="mlops-sentiment-$ENV"
        fi
        
        echo "🧪 Running health checks..."
        
        # Port forward для тестирования
        kubectl port-forward -n $NAMESPACE service/sentiment-service 8080:8000 &
        PF_PID=$!
        
        # Даем время на установку port-forward
        sleep 10
        
        # Проверяем endpoints
        curl -f http://localhost:8080/health || (kill $PF_PID && exit 1)
        curl -f http://localhost:8080/metrics || (kill $PF_PID && exit 1)
        
        # Тестируем API
        curl -X POST http://localhost:8080/predict \
          -H "Content-Type: application/json" \
          -d '{"text": "This is a test message for '"$ENV"' environment"}' \
          -f || (kill $PF_PID && exit 1)
        
        # Останавливаем port-forward
        kill $PF_PID
        
        echo "✅ All health checks passed for $ENV environment!"

    - name: Cleanup temporary files
      if: always()
      run: |
        rm -rf k8s-${{ inputs.environment }}/
        rm -f kubeconfig

    - name: Notify deployment result
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        text: |
          🚀 Deployment to **${{ inputs.environment }}** environment
          **Status**: ${{ job.status == 'success' && '✅ Success' || '❌ Failed' }}
          **Image**: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}`
          **Replicas**: ${{ inputs.replicas }}
          **Commit**: ${{ github.sha }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Дополнительные проверки для production
  production-validation:
    needs: deploy
    runs-on: ubuntu-latest
    if: inputs.environment == 'prod'
    
    steps:
    - name: Extended production validation
      run: |
        echo "🔍 Running extended production validation..."
        
        # Здесь можно добавить дополнительные проверки:
        # - Проверка метрик производительности
        # - Валидация SLA
        # - Проверка интеграций
        # - Smoke tests критичных функций
        
        echo "✅ Extended validation completed"

    - name: Update monitoring dashboards
      run: |
        echo "📊 Updating monitoring dashboards for production deployment..."
        
        # Здесь можно добавить обновление дашбордов Grafana
        # или других систем мониторинга
        
        echo "✅ Monitoring dashboards updated"
