# Pull Request Workflow
# Быстрая проверка качества кода для PR без развертывания

name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

# Отменяем предыдущие запуски для того же PR
concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # Быстрая проверка кода
  quick-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Получаем полную историю для лучшего анализа
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov black flake8 isort mypy bandit safety

    - name: Security check with bandit
      run: bandit -r app/ -f json -o bandit-report.json
      continue-on-error: true

    - name: Safety check for vulnerabilities
      run: safety check --json --output safety-report.json
      continue-on-error: true

    - name: Code quality checks
      run: |
        echo "=== Code Formatting Check ==="
        black --check --diff app/ tests/ || echo "❌ Formatting issues found"
        
        echo "=== Import Sorting Check ==="
        isort --check-only --diff app/ tests/ || echo "❌ Import sorting issues found"
        
        echo "=== Linting Check ==="
        flake8 app/ tests/ --statistics || echo "❌ Linting issues found"
        
        echo "=== Type Checking ==="
        mypy app/ --ignore-missing-imports || echo "❌ Type checking issues found"

    - name: Run tests
      run: |
        pytest tests/ -v --cov=app --cov-report=term-missing --cov-fail-under=80
      env:
        MLOPS_DEBUG: true

    - name: Comment PR with results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const fs = require('fs');
          
          let comment = '## 🔍 Code Quality Report\n\n';
          
          // Проверяем результаты тестов
          const testResult = '${{ job.status }}' === 'success' ? '✅ Passed' : '❌ Failed';
          comment += `**Tests**: ${testResult}\n`;
          
          // Добавляем информацию о покрытии
          comment += '\n### 📊 Test Coverage\n';
          comment += 'Coverage report will be available in the action logs.\n';
          
          // Добавляем советы по улучшению
          if ('${{ job.status }}' !== 'success') {
            comment += '\n### 💡 Next Steps\n';
            comment += '- Check the failed jobs above\n';
            comment += '- Run `black app/ tests/` to fix formatting\n';
            comment += '- Run `isort app/ tests/` to fix imports\n';
            comment += '- Run `pytest tests/` locally to verify tests pass\n';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  # Проверка Docker сборки без публикации
  docker-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (test only)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: sentiment-service:pr-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run --rm -d -p 8000:8000 --name test-container sentiment-service:pr-test
        sleep 30
        
        # Проверяем health endpoint
        curl -f http://localhost:8000/health || exit 1
        
        # Останавливаем контейнер
        docker stop test-container

  # Анализ изменений в Kubernetes манифестах
  k8s-manifest-check:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'k8s/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubeval
      run: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin

    - name: Validate Kubernetes manifests
      run: |
        for file in k8s/*.yaml; do
          echo "Validating $file"
          kubeval "$file"
        done

    - name: Check for resource limits
      run: |
        echo "Checking for resource limits in deployments..."
        if ! grep -q "resources:" k8s/deployment.yaml; then
          echo "❌ Warning: No resource limits found in deployment.yaml"
          exit 1
        fi
        echo "✅ Resource limits found"
